import type { Metadata } from "next";
import "./index.css";
import { GeistSans } from "geist/font/sans";
import Navbar from "@/Components/Home/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
// import MobileNav from "@/Components/Home/MobileNav/MobileNav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        {/* <div className="content"> */}
          <Navbar />
          {/* <MobileNav/> */}
          {children}
          <Footer />
        {/* </div> */}
      </body>
    </html>
  );
}
